[build]
  direction = "dist"
  command = "npm run build"

[[redirects]]
  from = "/sign-up"
  to = "/"
  status = 200

[[redirects]]
  from = "/messenger"
  to = "/"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/"
  status = 200

[[redirects]]
  from = "/edit-settings"
  to = "/"
  status = 200

[[redirects]]
  from = "/edit-password"
  to = "/"
  status = 200
